### ISSUE TITLE
Vite SSR fails to evaluate module. Unknown file extension ".css"

### ISSUE THREAD

**Issue by kolchurinvv** [beercss/beercss#162]
From what I can tell, this is related to #111 however, I understand that my case is an edge scenario:
i'm trying out svelte kit with bun as the runtime for 'production' and the package manager, however the build tool has to be vite, since bun doesn't fully support svelte-kit building yet, and `bun dev` is giving me a 404 error (still figuring this out 😄). with that i have to basically just run a vite dev server via node 18.x --lts.

i've got a `+layout.svelte` file that's responsible for the layout and the dark/light theme change across the app. i've tried importing beercss inside the `<script>` of the layout component like `import "beercss"` and like `import beercss from "beercss"` - makes no difference.
there error is:
```bash

  VITE v4.3.9  ready in 636 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://192.168.0.175:5173/
  ➜  press h to show help
11:48:30 AM [vite] Error when evaluating SSR module /src/routes/+layout.svelte: failed to import "beercss"
|- TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for /Users/vladimir/Dev_Projects/lime812/node_modules/beercss/dist/cdn/beer.min.css
    at new NodeError (node:internal/errors:399:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34)

Internal server error: Unknown file extension ".css" for /Users/vladimir/Dev_Projects/lime812/node_modules/beercss/dist/cdn/beer.min.css
      at new NodeError (node:internal/errors:399:5)
      at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
      at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
      at defaultLoad (node:internal/modules/esm/load:81:20)
      at nextLoad (node:internal/modules/esm/loader:163:28)
      at ESMLoader.load (node:internal/modules/esm/loader:605:26)
      at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
      at new ModuleJob (node:internal/modules/esm/module_job:64:26)
      at #createModuleJob (node:internal/modules/esm/loader:480:17)
      at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34)
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for /Users/vladimir/Dev_Projects/lime812/node_modules/beercss/dist/cdn/beer.min.css
    at new NodeError (node:internal/errors:399:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
Internal server error: Unknown file extension ".css" for /Users/vladimir/Dev_Projects/lime812/node_modules/beercss/dist/cdn/beer.min.css
      at new NodeError (node:internal/errors:399:5)
      at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
      at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
      at defaultLoad (node:internal/modules/esm/load:81:20)
      at nextLoad (node:internal/modules/esm/loader:163:28)
      at ESMLoader.load (node:internal/modules/esm/loader:605:26)
      at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
      at new ModuleJob (node:internal/modules/esm/module_job:64:26)
      at #createModuleJob (node:internal/modules/esm/loader:480:17)
      at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) (x2)
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for /Users/vladimir/Dev_Projects/lime812/node_modules/beercss/dist/cdn/beer.min.css
    at new NodeError (node:internal/errors:399:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
Waiting for the debugger to disconnect...
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ELOOP: too many symbolic links encountered, stat '/opt/homebrew/Library/Homebrew/vendor/gems/mechanize-2.9.1/mechanize-2.9.1'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///Users/vladimir/Dev_Projects/lime812/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:52169:10)
    at FsEventsHandler._handleFsEventsSymlink (file:///Users/vladimir/Dev_Projects/lime812/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:51395:18) {
  errno: -62,
  code: 'ELOOP',
  syscall: 'stat',
  path: '/opt/homebrew/Library/Homebrew/vendor/gems/mechanize-2.9.1/mechanize-2.9.1'
}

Node.js v18.16.0
error: script "dev" exited with code 1 (SIGHUP)
```

let me know if I can help, coz i **LOVE** this Beercss! if you guys came out earlier, I might have liked UI development :) 
For the time being, importing it via a script tag in app.html from a cdn does the trick, however bundling it would be better imo

**Comment by myrp-leonardo** [comment]
I think the Beer CSS should be imported one time in a app level (not in components). SSR don't import css files like SPA. They have a custom way to import css files. So you need to use the manual import of Beer CSS:

👉 https://github.com/beercss/beercss/blob/main/docs/INDEX.md

**Comment by kolchurinvv** [comment]
ok. i'm pretty new with svelte and svelte-kit. how would i import it into svelte-kit project on an app level? in svelte there would be something like app.ts and app.svelte in src folder, but svelte-kit doesn't have them. so i used the +layout.svelte as "app level" import

**Comment by KicKerBNU** [comment]
@kolchurinvv 

Here its one example how you can use Svelte with Beercss locally 
https://github.com/KicKerBNU/svelte-app/tree/example-npm-svelte-beercss

Master branch uses a CDN in the app.html
https://github.com/KicKerBNU/svelte-app

Hope it helps you 🍺

**Comment by kolchurinvv** [comment]
@KicKerBNU @myrp-leonardo thank you both for helping!

i'm using the cdn in the html file right now actually. and while it's certainly A way to go, i was hoping to get a better understanding how app level libraries can be handled in a svelte kit project.

this is the repo i've created using beercss, feel free to poke around https://github.com/kolchurinvv/lime812
(first time using svelte, be gentle)

question: if i create the app.js file and import Beercss in it, do i have to import the app.js file in every +page and/or layout component? at least that's the feeling i'm getting based on the +page.svelte component in your repo. if that's the case, feels kinda clunky, no?

**Comment by KicKerBNU** [comment]
Hello @kolchurinvv,

You are right. I looked in some other examples using Svelte and i see they imported in the "app.html"

You can change your import from CDN to node modules:
`<link rel="stylesheet" href="/node_modules/beercss/dist/cdn/beer.min.css">`
Im having problems with the import of the new Javascript Module
`<script type="module" src="/node_modules/beercss/dist/cdn/beer.min.js"></script>`

Here on this bootstrap example they are using the import directly in the html too
https://blog.makeinfo.co/bootstrap-5-sveltekit

I dont work with Svelte but seems like a common practice using Svelte with Svelte Kit

**Comment by kolchurinvv** [comment]
@KicKerBNU quick follow up. i found how a similar framework is handled in this project: https://github.com/Leftium/multi-launch/blob/b1071f26926afe752b2c92593cfde1b4c0d06681/src/routes/%2Bpage.

i've pulled in '@picocss/pico' into my own repo to see whether it was how they're packaging differently somehow vs I'm importing libraries wrong. the result is that whatever they're doing - works. just using `import "@picocss/pico"` inside the  `src/+layout.svelte` applies their styles across the entire app.

**Comment by kolchurinvv** [comment]
Alright, @Blackman99 actually helped me out in the svelte discord. the way to make beercss work is this:
```
// vite.config.js
import { defineConfig } from 'vite'
export default defineConfig({
  ssr: {
    noExternal: ['beercss']
  }
})
```

**Comment by KicKerBNU** [comment]
Thank you for the follow up, this thread could help any other svelte developer's in the future.
