### ISSUE TITLE
Nuxt.js Syntax error

### ISSUE THREAD

**Issue by Ronjar** [beercss/beercss#275]
When importing beercss in nuxtjs by npm install and adding it to modules nuxt shows the following error:

 SyntaxError: Unexpected token ':'
  at internalCompileFunction (node:internal/vm:73:18)
  at wrapSafe (node:internal/modules/cjs/loader:1153:20)
  at Module._compile (node:internal/modules/cjs/loader:1205:27)
  at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
  at Module.load (node:internal/modules/cjs/loader:1091:32)
  at Module._load (node:internal/modules/cjs/loader:938:12)
  at Module.require (node:internal/modules/cjs/loader:1115:19)
  at require (node:internal/modules/helpers:130:18)
  at jiti (node_modules\jiti\dist\jiti.js:1:254014)
  at LOCAL_PATH/node_modules/beercss/index.js:1:163

Maybe if you want to add nuxt support you could give it a look. Thanks in advance.

**Comment by leonardorafael** [comment]
We will close this issue by inactivity, fell free to reopen it.
